version: '3'
services:
  feems:
    container_name: feems
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./feems:/src/feems
      - ./input_data:/feems/input_data
    command: tail -f /dev/null
